/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ivanakasalo.gui;

import com.ivanakasalo.bl.*;
import com.ivanakasalo.model.*;
import java.awt.Color;
import java.util.List;

/**
 *
 * @author Ivana
 */
public class DoctorTreatment extends javax.swing.JFrame {

    private final IManager manager = new HospitalManager();

    public DoctorTreatment() {
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        Utilities.setFormLocation(this);
        this.setVisible(true);

        setPatientDataForEditing(Statics.patient);

        GuiUtilities.fillDdlWithObject(manager.getSexes(), ddlFullSex);
        GuiUtilities.fillDdlBoolean(ddlFullAcohol);
        GuiUtilities.fillDdlBoolean(ddlFullHomeFood);
        GuiUtilities.fillDdlBoolean(ddlFullVegetarian);
        GuiUtilities.fillDdlBoolean(ddlFullSmoker);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        navContainer = new javax.swing.JPanel();
        btnMedicalHistory = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRecordsHistory = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnPrescribe = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        container = new javax.swing.JLayeredPane();
        pnlRecordsHistory = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblMedicalHistory = new javax.swing.JTable();
        pnlPrescribe = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        lblSuccess = new javax.swing.JLabel();
        btnAddItem = new javax.swing.JButton();
        ddlMedication = new javax.swing.JComboBox<>();
        ddlTest = new javax.swing.JComboBox<>();
        ddlConsultation = new javax.swing.JComboBox<>();
        cbFollowUpAppointement = new javax.swing.JCheckBox();
        btnSendToReception = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtDateOfNewApp = new javax.swing.JTextField();
        pnlScrollPatientDetails = new javax.swing.JScrollPane();
        pnlFullReg = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtFullMiddleName = new javax.swing.JTextField();
        txtFullSurname = new javax.swing.JTextField();
        ddlFullSex = new javax.swing.JComboBox<>();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        txtFullStimulants = new javax.swing.JTextField();
        txtFullCoffe = new javax.swing.JTextField();
        txtFullSoftDrinks = new javax.swing.JTextField();
        txtFullDiabetic = new javax.swing.JTextField();
        txtFullRegularMeals = new javax.swing.JTextField();
        txtFullHyperTensitive = new javax.swing.JTextField();
        txtFullCardiac = new javax.swing.JTextField();
        txtFullRespiratory = new javax.swing.JTextField();
        txtFullDigestive = new javax.swing.JTextField();
        txtFullAllergies = new javax.swing.JTextField();
        txtFullOrthopedic = new javax.swing.JTextField();
        txtFullMuscular = new javax.swing.JTextField();
        txtFullNeurological = new javax.swing.JTextField();
        ddlFullSmoker = new javax.swing.JComboBox<>();
        ddlFullAcohol = new javax.swing.JComboBox<>();
        ddlFullVegetarian = new javax.swing.JComboBox<>();
        jLabel109 = new javax.swing.JLabel();
        jLabel110 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        emptyLblToFillSpace = new javax.swing.JLabel();
        txtFullDateofVirth = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtFullStatement = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtFullPreviousTreatment = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtFullHospitalTreated = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtFullMajorSurgeries = new javax.swing.JTextArea();
        txtFullSpecificDrugs = new javax.swing.JTextField();
        ddlFullHomeFood = new javax.swing.JComboBox<>();
        btnFullSendToDoctor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        navContainer.setLayout(new java.awt.GridLayout(6, 0));

        btnMedicalHistory.setBackground(new java.awt.Color(176, 224, 230));
        btnMedicalHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMedicalHistoryMouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(176, 224, 230));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ivanakasalo/icons/icons8_User_25px.png"))); // NOI18N
        jLabel1.setText("Medical History");

        javax.swing.GroupLayout btnMedicalHistoryLayout = new javax.swing.GroupLayout(btnMedicalHistory);
        btnMedicalHistory.setLayout(btnMedicalHistoryLayout);
        btnMedicalHistoryLayout.setHorizontalGroup(
            btnMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
            .addGroup(btnMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnMedicalHistoryLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        btnMedicalHistoryLayout.setVerticalGroup(
            btnMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
            .addGroup(btnMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnMedicalHistoryLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        navContainer.add(btnMedicalHistory);

        btnRecordsHistory.setBackground(new java.awt.Color(176, 224, 230));
        btnRecordsHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRecordsHistoryMouseClicked(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(176, 224, 230));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ivanakasalo/icons/icons8_User_25px.png"))); // NOI18N
        jLabel5.setText("Appointment History");

        javax.swing.GroupLayout btnRecordsHistoryLayout = new javax.swing.GroupLayout(btnRecordsHistory);
        btnRecordsHistory.setLayout(btnRecordsHistoryLayout);
        btnRecordsHistoryLayout.setHorizontalGroup(
            btnRecordsHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
            .addGroup(btnRecordsHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnRecordsHistoryLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        btnRecordsHistoryLayout.setVerticalGroup(
            btnRecordsHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
            .addGroup(btnRecordsHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnRecordsHistoryLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        navContainer.add(btnRecordsHistory);

        btnPrescribe.setBackground(new java.awt.Color(176, 224, 230));
        btnPrescribe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrescribeMouseClicked(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(176, 224, 230));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ivanakasalo/icons/icons8_Send_File_25px_2.png"))); // NOI18N
        jLabel6.setText("Prescibe");

        javax.swing.GroupLayout btnPrescribeLayout = new javax.swing.GroupLayout(btnPrescribe);
        btnPrescribe.setLayout(btnPrescribeLayout);
        btnPrescribeLayout.setHorizontalGroup(
            btnPrescribeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
            .addGroup(btnPrescribeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnPrescribeLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        btnPrescribeLayout.setVerticalGroup(
            btnPrescribeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
            .addGroup(btnPrescribeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnPrescribeLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        navContainer.add(btnPrescribe);

        jPanel1.add(navContainer);

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        container.setLayout(new java.awt.BorderLayout());

        pnlRecordsHistory.setBackground(new java.awt.Color(255, 102, 255));
        pnlRecordsHistory.setLayout(new java.awt.GridBagLayout());

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel44.setText("Medical History");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 4, 1, 0);
        pnlRecordsHistory.add(jLabel44, gridBagConstraints);

        jLabel45.setText("Medication:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 0);
        pnlRecordsHistory.add(jLabel45, gridBagConstraints);

        jLabel46.setText("Test:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 4, 1, 0);
        pnlRecordsHistory.add(jLabel46, gridBagConstraints);

        jLabel47.setText("Consultation:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 4, 1, 0);
        pnlRecordsHistory.add(jLabel47, gridBagConstraints);

        jLabel48.setText("Follow-up Apponitment:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 4, 1, 0);
        pnlRecordsHistory.add(jLabel48, gridBagConstraints);

        tblMedicalHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Date", "Medicine", "Test", "Consultation"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMedicalHistory.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(tblMedicalHistory);
        if (tblMedicalHistory.getColumnModel().getColumnCount() > 0) {
            tblMedicalHistory.getColumnModel().getColumn(1).setResizable(false);
            tblMedicalHistory.getColumnModel().getColumn(3).setResizable(false);
        }

        pnlRecordsHistory.add(jScrollPane5, new java.awt.GridBagConstraints());

        container.add(pnlRecordsHistory, java.awt.BorderLayout.CENTER);

        pnlPrescribe.setBackground(new java.awt.Color(102, 255, 153));
        pnlPrescribe.setLayout(new java.awt.GridBagLayout());

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel39.setText("Prescribe:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 4, 1, 0);
        pnlPrescribe.add(jLabel39, gridBagConstraints);

        jLabel40.setText("Medication:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 0);
        pnlPrescribe.add(jLabel40, gridBagConstraints);

        jLabel41.setText("Test:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 4, 1, 0);
        pnlPrescribe.add(jLabel41, gridBagConstraints);

        jLabel42.setText("Consultation:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 4, 1, 0);
        pnlPrescribe.add(jLabel42, gridBagConstraints);

        jLabel43.setText("Follow-up Apponitment:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 4, 1, 0);
        pnlPrescribe.add(jLabel43, gridBagConstraints);

        lblSuccess.setText("Succes placeholder");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 4, 1, 0);
        pnlPrescribe.add(lblSuccess, gridBagConstraints);

        btnAddItem.setText("Prescribe");
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        pnlPrescribe.add(btnAddItem, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        pnlPrescribe.add(ddlMedication, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        pnlPrescribe.add(ddlTest, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        pnlPrescribe.add(ddlConsultation, gridBagConstraints);

        cbFollowUpAppointement.setText("Yes");
        cbFollowUpAppointement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFollowUpAppointementActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        pnlPrescribe.add(cbFollowUpAppointement, gridBagConstraints);

        btnSendToReception.setText("Send to Reception");
        btnSendToReception.setEnabled(false);
        btnSendToReception.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendToReceptionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        pnlPrescribe.add(btnSendToReception, gridBagConstraints);

        jLabel2.setText("Date of follow up appontment:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        pnlPrescribe.add(jLabel2, gridBagConstraints);

        txtDateOfNewApp.setText("jTextField1");
        txtDateOfNewApp.setEnabled(false);
        txtDateOfNewApp.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        pnlPrescribe.add(txtDateOfNewApp, gridBagConstraints);

        container.add(pnlPrescribe, java.awt.BorderLayout.CENTER);

        pnlFullReg.setBackground(new java.awt.Color(153, 153, 255));
        pnlFullReg.setLayout(new java.awt.GridBagLayout());

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setText("Date:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 4, 1, 0);
        pnlFullReg.add(jLabel30, gridBagConstraints);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setText("Basic Details");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 4, 1, 0);
        pnlFullReg.add(jLabel31, gridBagConstraints);

        jLabel32.setText("OPID:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 0);
        pnlFullReg.add(jLabel32, gridBagConstraints);

        jLabel33.setText("First name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 4, 1, 0);
        pnlFullReg.add(jLabel33, gridBagConstraints);

        jLabel34.setText("Middle name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 4, 1, 0);
        pnlFullReg.add(jLabel34, gridBagConstraints);

        jLabel35.setText("Surname:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 4, 1, 0);
        pnlFullReg.add(jLabel35, gridBagConstraints);

        jLabel36.setText("Sex:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 0);
        pnlFullReg.add(jLabel36, gridBagConstraints);

        jLabel37.setText("Date of Birth:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 4, 1, 0);
        pnlFullReg.add(jLabel37, gridBagConstraints);

        txtFirstName.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 1, 0);
        pnlFullReg.add(txtFirstName, gridBagConstraints);

        txtFullMiddleName.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 1, 0);
        pnlFullReg.add(txtFullMiddleName, gridBagConstraints);

        txtFullSurname.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 1, 0);
        pnlFullReg.add(txtFullSurname, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 1, 0);
        pnlFullReg.add(ddlFullSex, gridBagConstraints);

        jLabel86.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel86.setText("Lifestyle");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 36, 1, 0);
        pnlFullReg.add(jLabel86, gridBagConstraints);

        jLabel87.setText("Vegetarian/Non-Vegetarian:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 36, 1, 0);
        pnlFullReg.add(jLabel87, gridBagConstraints);

        jLabel88.setText("Smoker (Y/N):)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 36, 1, 0);
        pnlFullReg.add(jLabel88, gridBagConstraints);

        jLabel90.setText("Consumes Alocholic Beverage (Y/N):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 36, 1, 0);
        pnlFullReg.add(jLabel90, gridBagConstraints);

        jLabel92.setText("Consumption of Soft Drinks/Day:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 36, 1, 0);
        pnlFullReg.add(jLabel92, gridBagConstraints);

        jLabel93.setText("Have regular Meals/Breafast/Lunch/Dinner)?:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 36, 1, 0);
        pnlFullReg.add(jLabel93, gridBagConstraints);

        jLabel94.setText("Eat Home Food Predominantly?:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 36, 1, 0);
        pnlFullReg.add(jLabel94, gridBagConstraints);

        jLabel95.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel95.setText("Important Medical Complaints");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 36, 1, 0);
        pnlFullReg.add(jLabel95, gridBagConstraints);

        jLabel96.setText("Diabetic:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 36, 1, 0);
        pnlFullReg.add(jLabel96, gridBagConstraints);

        jLabel97.setText("HyperTensive:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 36, 1, 0);
        pnlFullReg.add(jLabel97, gridBagConstraints);

        jLabel98.setText("Use Stimulants(Specify):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 36, 1, 0);
        pnlFullReg.add(jLabel98, gridBagConstraints);

        jLabel99.setText("Consumption of Coffee-Tea/Day:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 36, 1, 0);
        pnlFullReg.add(jLabel99, gridBagConstraints);

        jLabel100.setText("Cardiac Condition:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 36, 1, 0);
        pnlFullReg.add(jLabel100, gridBagConstraints);

        jLabel101.setText("Resporatory Condition:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 36, 1, 0);
        pnlFullReg.add(jLabel101, gridBagConstraints);

        jLabel102.setText("Digestive Condition:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 36, 1, 0);
        pnlFullReg.add(jLabel102, gridBagConstraints);

        jLabel103.setText("Orthopedic Condition:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 36, 1, 0);
        pnlFullReg.add(jLabel103, gridBagConstraints);

        jLabel104.setText("Muscular Condition:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 36, 1, 0);
        pnlFullReg.add(jLabel104, gridBagConstraints);

        jLabel105.setText("Neurological Condition:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 36, 1, 0);
        pnlFullReg.add(jLabel105, gridBagConstraints);

        jLabel106.setText("Know Allergies:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 36, 1, 0);
        pnlFullReg.add(jLabel106, gridBagConstraints);

        jLabel107.setText("Known Adverse Reaction to Specific Drugs:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 36, 1, 0);
        pnlFullReg.add(jLabel107, gridBagConstraints);

        jLabel108.setText("Major Surgeries (History):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 36, 1, 0);
        pnlFullReg.add(jLabel108, gridBagConstraints);

        txtFullStimulants.setText("jTextField46");
        txtFullStimulants.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 9, 1, 0);
        pnlFullReg.add(txtFullStimulants, gridBagConstraints);

        txtFullCoffe.setText("jTextField49");
        txtFullCoffe.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 9, 1, 0);
        pnlFullReg.add(txtFullCoffe, gridBagConstraints);

        txtFullSoftDrinks.setText("jTextField50");
        txtFullSoftDrinks.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 9, 1, 0);
        pnlFullReg.add(txtFullSoftDrinks, gridBagConstraints);

        txtFullDiabetic.setText("jTextField51");
        txtFullDiabetic.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 9, 1, 0);
        pnlFullReg.add(txtFullDiabetic, gridBagConstraints);

        txtFullRegularMeals.setText("jTextField53");
        txtFullRegularMeals.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 9, 1, 0);
        pnlFullReg.add(txtFullRegularMeals, gridBagConstraints);

        txtFullHyperTensitive.setText("jTextField54");
        txtFullHyperTensitive.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 9, 1, 0);
        pnlFullReg.add(txtFullHyperTensitive, gridBagConstraints);

        txtFullCardiac.setText("jTextField55");
        txtFullCardiac.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 9, 1, 0);
        pnlFullReg.add(txtFullCardiac, gridBagConstraints);

        txtFullRespiratory.setText("jTextField56");
        txtFullRespiratory.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 9, 1, 0);
        pnlFullReg.add(txtFullRespiratory, gridBagConstraints);

        txtFullDigestive.setText("jTextField57");
        txtFullDigestive.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 9, 1, 0);
        pnlFullReg.add(txtFullDigestive, gridBagConstraints);

        txtFullAllergies.setText("jTextField59");
        txtFullAllergies.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 9, 1, 0);
        pnlFullReg.add(txtFullAllergies, gridBagConstraints);

        txtFullOrthopedic.setText("jTextField60");
        txtFullOrthopedic.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 9, 1, 0);
        pnlFullReg.add(txtFullOrthopedic, gridBagConstraints);

        txtFullMuscular.setText("jTextField61");
        txtFullMuscular.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 9, 1, 0);
        pnlFullReg.add(txtFullMuscular, gridBagConstraints);

        txtFullNeurological.setText("jTextField62");
        txtFullNeurological.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 9, 1, 0);
        pnlFullReg.add(txtFullNeurological, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 9, 1, 0);
        pnlFullReg.add(ddlFullSmoker, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 9, 1, 0);
        pnlFullReg.add(ddlFullAcohol, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 9, 1, 0);
        pnlFullReg.add(ddlFullVegetarian, gridBagConstraints);

        jLabel109.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel109.setText("Basic Complaints:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 36, 1, 0);
        pnlFullReg.add(jLabel109, gridBagConstraints);

        jLabel110.setText("Statement of Complaint:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 36, 1, 0);
        pnlFullReg.add(jLabel110, gridBagConstraints);

        jLabel111.setText("History of Previous Treatment:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 36, 1, 0);
        pnlFullReg.add(jLabel111, gridBagConstraints);

        jLabel112.setText("Physician/Hospital Treated:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 36, 1, 0);
        pnlFullReg.add(jLabel112, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 10.0;
        gridBagConstraints.weighty = 30.0;
        pnlFullReg.add(emptyLblToFillSpace, gridBagConstraints);

        txtFullDateofVirth.setText("jTextField17");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        pnlFullReg.add(txtFullDateofVirth, gridBagConstraints);

        txtFullStatement.setColumns(20);
        txtFullStatement.setRows(5);
        jScrollPane1.setViewportView(txtFullStatement);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 22;
        pnlFullReg.add(jScrollPane1, gridBagConstraints);

        txtFullPreviousTreatment.setColumns(20);
        txtFullPreviousTreatment.setRows(5);
        jScrollPane2.setViewportView(txtFullPreviousTreatment);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 23;
        pnlFullReg.add(jScrollPane2, gridBagConstraints);

        txtFullHospitalTreated.setColumns(20);
        txtFullHospitalTreated.setRows(5);
        jScrollPane3.setViewportView(txtFullHospitalTreated);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 24;
        pnlFullReg.add(jScrollPane3, gridBagConstraints);

        txtFullMajorSurgeries.setColumns(20);
        txtFullMajorSurgeries.setRows(5);
        jScrollPane4.setViewportView(txtFullMajorSurgeries);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 19;
        pnlFullReg.add(jScrollPane4, gridBagConstraints);

        txtFullSpecificDrugs.setText("jTextField25");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 19;
        pnlFullReg.add(txtFullSpecificDrugs, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 17;
        pnlFullReg.add(ddlFullHomeFood, gridBagConstraints);

        btnFullSendToDoctor.setText("Refer to Specialist");
        btnFullSendToDoctor.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        pnlFullReg.add(btnFullSendToDoctor, gridBagConstraints);

        pnlScrollPatientDetails.setViewportView(pnlFullReg);

        container.add(pnlScrollPatientDetails, java.awt.BorderLayout.CENTER);

        jPanel2.add(container, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMedicalHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMedicalHistoryMouseClicked
        GuiUtilities.changePanel(container, pnlScrollPatientDetails);
        GuiUtilities.fillDdlWithObject(manager.getSexes(), ddlFullSex);
        GuiUtilities.fillDdlBoolean(ddlFullAcohol);
        GuiUtilities.fillDdlBoolean(ddlFullHomeFood);
        GuiUtilities.fillDdlBoolean(ddlFullVegetarian);
        GuiUtilities.fillDdlBoolean(ddlFullSmoker);

    }//GEN-LAST:event_btnMedicalHistoryMouseClicked

    private void btnRecordsHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecordsHistoryMouseClicked
        GuiUtilities.changePanel(container, pnlRecordsHistory);
        fillTableMedicalHistory();
    }//GEN-LAST:event_btnRecordsHistoryMouseClicked

    private void btnPrescribeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrescribeMouseClicked
        GuiUtilities.changePanel(container, pnlPrescribe);
        GuiUtilities.fillDdlWithObject(manager.getTests(), ddlTest);
        GuiUtilities.fillDdlWithObject(manager.getMedicines(), ddlMedication);
        GuiUtilities.fillDdlWithObject(manager.getConsultations(), ddlConsultation);
    }//GEN-LAST:event_btnPrescribeMouseClicked

    private void btnSendToReceptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendToReceptionActionPerformed
        Statics.patiensToBeCharged.add(Statics.patient);
        this.dispose();


    }//GEN-LAST:event_btnSendToReceptionActionPerformed

    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed
        Medicine medication = (Medicine) ddlMedication.getSelectedItem();
        Test test = (Test) ddlTest.getSelectedItem();
        Consultation consultation = (Consultation) ddlConsultation.getSelectedItem();

        Item item = new Item(medication, test, consultation, Statics.patient);

        try {
            manager.addItem(item);
            lblSuccess.setText("Item added successfully");
            btnSendToReception.setEnabled(true);
        } catch (Exception e) {
            lblSuccess.setText("Item NOT added successfully");
            lblSuccess.setForeground(Color.red);
        }

        if (txtDateOfNewApp.isEnabled() && !txtDateOfNewApp.getText().equals("")) {
            manager.addFutureAppointement(Statics.patient, Statics.doctor, Utilities.getSqlDate(txtDateOfNewApp.getText()));
        }


    }//GEN-LAST:event_btnAddItemActionPerformed

    private void cbFollowUpAppointementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFollowUpAppointementActionPerformed
        txtDateOfNewApp.setEnabled(!txtDateOfNewApp.isEnabled());
    }//GEN-LAST:event_cbFollowUpAppointementActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorTreatment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorTreatment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorTreatment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorTreatment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorTreatment().setVisible(true);
            }
        });
    }

    private void fillTableMedicalHistory() {
        if (manager.getItemsPerPatient(Statics.patient) != null) {
            List<Item> items = manager.getItemsPerPatient(Statics.patient);
            Object rowData[] = new Object[5];

            for (int i = 0; i < items.size(); i++) {
                rowData[0] = items.get(i).getEntryDate();
                rowData[1] = items.get(i).getMedicine().getMedicine();
                rowData[2] = items.get(i).getTest().getName();
                rowData[3] = items.get(i).getConsultation().getConsultation();

                GuiUtilities.getModel(tblMedicalHistory).addRow(rowData);
            }

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnFullSendToDoctor;
    private javax.swing.JPanel btnMedicalHistory;
    private javax.swing.JPanel btnPrescribe;
    private javax.swing.JPanel btnRecordsHistory;
    private javax.swing.JButton btnSendToReception;
    private javax.swing.JCheckBox cbFollowUpAppointement;
    private javax.swing.JLayeredPane container;
    private javax.swing.JComboBox<String> ddlConsultation;
    private javax.swing.JComboBox<String> ddlFullAcohol;
    private javax.swing.JComboBox<String> ddlFullHomeFood;
    private javax.swing.JComboBox<String> ddlFullSex;
    private javax.swing.JComboBox<String> ddlFullSmoker;
    private javax.swing.JComboBox<String> ddlFullVegetarian;
    private javax.swing.JComboBox<String> ddlMedication;
    private javax.swing.JComboBox<String> ddlTest;
    private javax.swing.JLabel emptyLblToFillSpace;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblSuccess;
    private javax.swing.JPanel navContainer;
    private javax.swing.JPanel pnlFullReg;
    private javax.swing.JPanel pnlPrescribe;
    private javax.swing.JPanel pnlRecordsHistory;
    private javax.swing.JScrollPane pnlScrollPatientDetails;
    private javax.swing.JTable tblMedicalHistory;
    private javax.swing.JTextField txtDateOfNewApp;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtFullAllergies;
    private javax.swing.JTextField txtFullCardiac;
    private javax.swing.JTextField txtFullCoffe;
    private javax.swing.JTextField txtFullDateofVirth;
    private javax.swing.JTextField txtFullDiabetic;
    private javax.swing.JTextField txtFullDigestive;
    private javax.swing.JTextArea txtFullHospitalTreated;
    private javax.swing.JTextField txtFullHyperTensitive;
    private javax.swing.JTextArea txtFullMajorSurgeries;
    private javax.swing.JTextField txtFullMiddleName;
    private javax.swing.JTextField txtFullMuscular;
    private javax.swing.JTextField txtFullNeurological;
    private javax.swing.JTextField txtFullOrthopedic;
    private javax.swing.JTextArea txtFullPreviousTreatment;
    private javax.swing.JTextField txtFullRegularMeals;
    private javax.swing.JTextField txtFullRespiratory;
    private javax.swing.JTextField txtFullSoftDrinks;
    private javax.swing.JTextField txtFullSpecificDrugs;
    private javax.swing.JTextArea txtFullStatement;
    private javax.swing.JTextField txtFullStimulants;
    private javax.swing.JTextField txtFullSurname;
    // End of variables declaration//GEN-END:variables

    private void setPatientDataForEditing(Patient patient) {
        txtFirstName.setText(patient.getFirstName());
        txtFullMiddleName.setText(patient.getMiddleName());
        txtFullSurname.setText(patient.getSurname());
        txtFullDateofVirth.setText(String.valueOf(patient.getDateOfBirth()));
        txtFullStimulants.setText(patient.getStimulants());
        txtFullCoffe.setText(String.valueOf(patient.getCoffeeTeaDay()));
        txtFullSoftDrinks.setText(String.valueOf(patient.getSoftDrinksDay()));
        txtFullRegularMeals.setText(patient.getRegularMeals());
        txtFullStatement.setText(patient.getStatementOfComplaint());
        txtFullPreviousTreatment.setText(patient.getPreviousTreatments());
        txtFullHospitalTreated.setText(patient.getPhysicianHospitalTreated());
        txtFullDiabetic.setText(patient.getDiabetic());
        txtFullHyperTensitive.setText(patient.getHypertensive());
        txtFullCardiac.setText(patient.getCardiacCondition());
        txtFullRespiratory.setText(patient.getRespiratoryCondition());
        txtFullDigestive.setText(patient.getDigestiveCondition());
        txtFullOrthopedic.setText(patient.getOrthopedicCondtion());
        txtFullMuscular.setText(patient.getMuscularCondition());
        txtFullAllergies.setText(patient.getKnownAllergies());
        txtFullSpecificDrugs.setText(patient.getKnownReactionToSpecificDrug());
        txtFullMajorSurgeries.setText(patient.getMajorSurgeriesHistory());

    }

}
